// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9BdUrHvTddt_G7judeisChq5KkEtkHwc',
    appId: '1:884517494742:web:6784f7c9c40126030a8e77',
    messagingSenderId: '884517494742',
    projectId: 'practice-1-flutter-app',
    authDomain: 'practice-1-flutter-app.firebaseapp.com',
    storageBucket: 'practice-1-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJr2Lmh-fxM3Wjh8MX4iueTh9ida0BwE8',
    appId: '1:884517494742:android:5baf9dc15ccc97440a8e77',
    messagingSenderId: '884517494742',
    projectId: 'practice-1-flutter-app',
    storageBucket: 'practice-1-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTPabKGf3CajsKY4BoEz8cMqb1n3N3aWg',
    appId: '1:884517494742:ios:c3b5271e90516a710a8e77',
    messagingSenderId: '884517494742',
    projectId: 'practice-1-flutter-app',
    storageBucket: 'practice-1-flutter-app.appspot.com',
    iosBundleId: 'com.example.prac1App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTPabKGf3CajsKY4BoEz8cMqb1n3N3aWg',
    appId: '1:884517494742:ios:3a7d5f2ee68118330a8e77',
    messagingSenderId: '884517494742',
    projectId: 'practice-1-flutter-app',
    storageBucket: 'practice-1-flutter-app.appspot.com',
    iosBundleId: 'com.example.prac1App.RunnerTests',
  );
}
